name: ci

on:
  push:
    branches:
      - main

jobs:
  test-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions.checkout@v1

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Test Run
        run: docker-compose start

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
